In [63]:
import numpy as np


In [64]:
G = [
    [1,0,1,0],
    [1,0,1,1],
    [0,1,1,0],
    [1,0,0,0]
]

In [68]:
A = np.array(G)
print(A)

[[1 0 1 0]
 [1 0 1 1]
 [0 1 1 0]
 [1 0 0 0]]


In [70]:
for i in range(len(A)):
    for j in range(len(A)):
        if (A[i,j] == 1):
            print(f"{chr(i+97)} -> {chr(j+97)}")

a -> a
a -> c
b -> a
b -> c
b -> d
c -> b
c -> c
d -> a


In [66]:
import graphviz as gv
def dibujarGrafo(A):
    grafo = gv.Digraph("grafo2d")
    n = len(A)
    for i in range(n):
        for j in range(n):
            if (A[i,j] == 1):
                grafo.edge(str(i+1), str(j+1))
    return grafo

In [67]:
migrafo = dibujarGrafo(A)
print(migrafo)

digraph grafo2d {
	1 -> 1
	1 -> 3
	2 -> 1
	2 -> 3
	2 -> 4
	3 -> 2
	3 -> 3
	4 -> 1
}



In [ ]:
#migrafo

#Guardamos la matriz de adyacencia en un archivo
%%file file_matrizd2.txt
1 0 1 0
1 0 1 1
0 1 1 0
1 0 0 0 

#Leer el Archivo
A2 = np.loadtxt("file_matrizd2.xtx", dtype=int)
print(A2)

In [ ]:
DibujarGrafo(A2)